### ISSUE TITLE
Mustache does not work if control is in a multicolumn

### ISSUE THREAD

**Issue by josemaldonad0** [ProcessMaker/bpm#984] opened 2018-12-01 02:46 UTC
In Screen Builder, text box controls that include mustache tags will not be identified as such if these boxes are placed within multi-columns. Instead, the mustaches will display as part of the text.

Outside, the same controls will be properly rendered.

**Comment by velkymx** [comment] 2018-12-03 17:31
Duplicate of #975

**Closed by velkymx** 2018-12-03 17:31 UTC
