### ISSUE TITLE
Horizon UUID Issue

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/bpm#793] opened 2018-10-22 16:42 UTC
The UUID that we are using as binary is having an issue with encoding and decoding the binary data. It is causing an issue with the Horizon reporting. 

@caleeli please provide additional details to troubleshoot and fix.

**Comment by caleeli** [comment] 2018-10-22 17:33
How to reproduce:

- From branch (https://github.com/ProcessMaker/bpm/tree/fixDefaultProcess) it has a fix for the script tasks.
- Start a new Request
![image](https://user-images.githubusercontent.com/8028650/47307704-b67eb700-d5fd-11e8-9723-b25c9f2182e0.png)

- In the log you could see:

```
[2018-10-22 17:19:51] testing.INFO: Script started: 5d36e5e6-d60c-11e8-b867-080027874bc2
[2018-10-22 17:19:55] testing.INFO: Script completed: 5d36e5e6-d60c-11e8-b867-080027874bc2
[2018-10-22 17:19:55] testing.ERROR: ERR Error running script (call to f_9bd406a64e43e31f0dde2849660e8cd56f340b85): @user_script:7: user_script:7: Expected value but found T_END at character 1  {"exception":"[object] (Predis\\Response\\ServerException(code: 0): ERR Error running script (call to f_9bd406a64e43e31f0dde2849660e8cd56f340b85): @user_script:7: user_script:7: Expected value but found T_END at character 1  at /opt/processmaker/vendor/predis/predis/src/Client.php:372)
[stacktrace]
#0 /opt/processmaker/vendor/predis/predis/src/Client.php(337): Predis\\Client->onErrorResponse(Object(Predis\\Command\\ServerEval), Object(Predis\\Response\\Error))
#1 /opt/processmaker/vendor/predis/predis/src/Client.php(314): Predis\\Client->executeCommand(Object(Predis\\Command\\ServerEval))
#2 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(114): Predis\\Client->__call('eval', Array)
#3 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(214): Illuminate\\Redis\\Connections\\Connection->command('eval', Array)
#4 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(223): Illuminate\\Redis\\Connections\\Connection->__call('eval', Array)
#5 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Queue/RedisQueue.php(166): Illuminate\\Queue\\RedisQueue->retrieveNextJob('queues:default')
#6 /opt/processmaker/vendor/laravel/horizon/src/RedisQueue.php(92): Illuminate\\Queue\\RedisQueue->pop('default')
#7 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(247): Laravel\\Horizon\\RedisQueue->pop('default')
#8 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(107): Illuminate\\Queue\\Worker->getNextJob(Object(Laravel\\Horizon\\RedisQueue), 'default')
#9 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(102): Illuminate\\Queue\\Worker->daemon('redis', 'default', Object(Illuminate\\Queue\\WorkerOptions))
#10 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(86): Illuminate\\Queue\\Console\\WorkCommand->runWorker('redis', 'default')
#11 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#12 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#13 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#14 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(ProcessMaker\\Application), Array, Object(Closure))
#15 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Container/Container.php(571): Illuminate\\Container\\BoundMethod::call(Object(ProcessMaker\\Application), Array, Array, NULL)
#16 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
#17 /opt/processmaker/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#18 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#19 /opt/processmaker/vendor/symfony/console/Application.php(886): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /opt/processmaker/vendor/symfony/console/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Illuminate\\Queue\\Console\\WorkCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /opt/processmaker/vendor/symfony/console/Application.php(145): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Console/Application.php(89): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /opt/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 /opt/processmaker/artisan(30): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#25 {main}
"}
```

The error **ERR Error running script (call to f_9bd406a64e43e31f0dde2849660e8cd56f340b85): @user_script:7: user_script:7: Expected value but found T_END at character 1  {"exception":"[object] (Predis\\Response\\ServerException(code: 0)...** looks like Horizon tries to execute a code in Redis to read a model using JSON encoding, but the job contains binary information which is not supported:

```
 -- Pop the first job off of the queue...
local job = redis.call('lpop', KEYS[1])
local reserved = false

if(job ~= false) then
    -- Increment the attempt count and place job on the reserved queue...
    reserved = cjson.decode(job)
    reserved['attempts'] = reserved['attempts'] + 1
    reserved = cjson.encode(reserved)
    redis.call('zadd', KEYS[2], ARGV[1], reserved)
end

return {job, reserved}
```
Actually all the properties uuids used in the Jobs are text strings (not binaries)

**Comment by tdondich** [comment] 2018-10-23 02:57
When not running horizon, it works just fine.  This isn't the bad queue job in question.

The problem is, when the job is processed (successfully), horizon is putting another job on the queue.  However, it appears this is a bad job, given this logged redis command:

1540263202.109517 [0 127.0.0.1:48002] "RPUSH" "queues:default" ""

Since the empty string is not valid json, that's what is tripping it up.

Tracing it now to what is causing that.

**Comment by tdondich** [comment] 2018-10-23 04:40
Code is fixed in bugfix/793 .  Note, at this time, it requires using a forked version of laravel horizon.

**Closed by tdondich** 2018-10-23 04:40 UTC
